### ISSUE TITLE
`/index.bundle` won't load app.config.ts 

### ISSUE THREAD

**Issue by Nasseratic** [expo/eas-tests-example#6]
Hello @dsokal 

Thanks for this amazing example for e2e, it was super useful for us.

In the example, you used a URL with `/index.bundle`
But that skips loading expo app.config.ts 
https://github.com/expo/eas-tests-example/blob/eca97443e671c488bb5eee805fdd5294eef0ae6f/e2e/tests/utils/openApp.js#L43

We tried to remove the `/index.bundle` of the URL, and the `app.config.ts` was loading correctly. 
Is there a reason to have `/index.bundle`  in the URL?

In both cases, ( with or without the `/index.bundle` ) ci is failing randomly when trying to load the bundle.

https://user-images.githubusercontent.com/18466484/210331942-89f48a86-e15a-42a5-89bd-7e0fb6cdaf8c.mp4

Hello @dsokal 

Thanks for this amazing example for e2e, it was super useful for us.

In the example, you used a URL with `/index.bundle`

But that skips loading expo app.config.ts 
https://github.com/expo/eas-tests-example/blob/eca97443e671c488bb5eee805fdd5294eef0ae6f/e2e/tests/utils/openApp.js#L43

Is there a reason to have `/index.bundle`  in the URL?
We tried to remove the `/index.bundle` of the URL, and the `app.config.ts` was loading correctly. 
But CI started to fail randomly when trying to load the bundle.

https://user-images.githubusercontent.com/18466484/210331942-89f48a86-e15a-42a5-89bd-7e0fb6cdaf8c.mp4

Side note:
We needed to call `await device.disableSynchronization()` without it I end up with random timeout :)

![image](https://user-images.githubusercontent.com/18466484/210352902-eb551995-755c-46cb-8b11-85c86256ed2f.png)

**Comment by douglowder** [comment]
@Nasseratic could you provide a project that produces the random failures and uses `app.config.ts`? I suspect that there might be some place in the test where we need to add an extra timeout.
